-- drop database if exists gpc;
-- create database gpc;

drop table if exists runrun;
drop table if exists runin;
drop table if exists runout;
drop table if exists run;
drop table if exists fso;
drop table if exists task;

-- state of task when run
create table task (
  id text primary key,
  define text,
  sysstate text
);

-- log of each run of a task
create table run (
  id text primary key,
  usr text,
  task text references task
  -- info
  -- timestamp
);

-- file system object
create table fso (
  id text primary key,
  path text,
  digest text
);

-- fsos generated by a run
create table runout (
  run text references run,
  fso text references fso,
  correct boolean, -- move to own table of actions
  primary key (run, fso)
);

-- fsos used as input by a run
-- needed for caching
create table runin (
  run text references run,
  fso text references fso,
  primary key (run, fso)
);

-- other run used as to generate input to a run
-- needed for provenance
create table runrun (
  run text references run,
  inputrun text references run,
  primary key (run, inputrun)
);
