-- drop database if exists gpc;
-- create database gpc;

drop table if exists depended;
drop table if exists used;
drop index if exists trust_run_path;
drop table if exists trust;
drop table if exists created;
drop index if exists run_calculation;
drop table if exists run;
drop table if exists usr;
drop table if exists calculation;
drop table if exists task;

-- state of task when run
create table task (
  id text primary key,
  definition text,
  sysstate text
);

create table calculation (
  id text primary key,
  task text references task
);

create table usr (
  id text primary key,
  name text
);

-- log of each run of a task
create table run (
  id text primary key,
  usr text references usr,
  calculation text references calculation,
  info text,
  time timestamp with time zone
);
create index run_calculation on run (calculation);

-- fsos generated by a run
create table created (
  run text references run,
  path text,
  digest text,
  primary key (run, path)
);

create table trust (
  run text,
  path text,
  usr text references usr,
  time timestamp with time zone,
  correct boolean,
  constraint fk foreign key (run, path) references created
);
-- is this the right index to use?
create index trust_run_path on trust (run, path);

-- fsos used as input by a calculation
-- needed for caching
create table used (
  calculation text references calculation,
  path text,
  digest text,
  primary key (calculation, path)
);

-- other run used as to generate input to a run
-- needed for provenance
create table depended (
  run text references run,
  inputrun text references run,
  primary key (run, inputrun)
);
